# Generated by Django 5.1.1 on 2024-09-24 02:55
#0001_initial.py 
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id_locacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_locacion', models.CharField(max_length=100)),
                ('descripcion_locacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_taller', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('requisito_asistencia', models.CharField(max_length=100)),
                ('creditos_taller', models.IntegerField()),
            ],
        ),
    ]
