# Generated by Django 5.1.1 on 2024-11-04 22:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('matricula_alumno', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'La matrícula debe tener exactamente 8 dígitos.')])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(editable=False, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id_locacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_locacion', models.CharField(max_length=100)),
                ('descripcion_locacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_taller', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RubricaReportes',
            fields=[
                ('id_rubrica_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('registro_de_participantes', models.FileField(blank=True, null=True, upload_to='rubricas/participantes/')),
                ('evaluacion_desempeno', models.FileField(blank=True, null=True, upload_to='rubricas/evaluacion/')),
            ],
        ),
        migrations.CreateModel(
            name='TalleresSupergrupo',
            fields=[
                ('id_taller_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=100)),
                ('estatus_taller', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='ConstanciaLiberacion',
            fields=[
                ('id_constancia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estatus_constancia', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Emitida', 'Emitida')], default='Pendiente', max_length=20)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.alumno')),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(editable=False, max_length=128)),
                ('genero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(max_length=10)),
                ('nivel_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.nivelacceso')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.nivelacceso'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('registro_participantes', models.FileField(blank=True, null=True, upload_to='reportes/participantes/')),
                ('evaluacion_desempeno', models.FileField(blank=True, null=True, upload_to='reportes/evaluacion/')),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.inscripcion')),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='TalleresSubgrupos',
            fields=[
                ('id_taller_registro', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_escolar', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('turno_taller', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('estatus_card', models.BooleanField(default=True)),
                ('dias_taller', models.CharField(max_length=200)),
                ('puntos_taller', models.IntegerField()),
                ('cupo_taller', models.IntegerField()),
                ('tipo_taller', models.CharField(max_length=100)),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.instructor')),
                ('id_taller_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.talleressupergrupo')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_taller_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.talleressubgrupos'),
        ),
        migrations.CreateModel(
            name='UsuarioAdmin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('contraseña', models.CharField(editable=False, max_length=128)),
                ('nivel_acceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talleres.nivelacceso')),
            ],
        ),
    ]
