# Generated by Django 5.1.1 on 2024-11-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='id_alumno',
            new_name='id_alum',
        ),
    ]
