# Generated by Django 5.1.1 on 2024-11-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constancialiberacion',
            name='estatus_constancia',
        ),
        migrations.RemoveField(
            model_name='constancialiberacion',
            name='id_inscripcion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id_inscripcion',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id_instructor',
        ),
        migrations.AddField(
            model_name='constancialiberacion',
            name='contancia_liberacion',
            field=models.FileField(blank=True, null=True, upload_to='contancia/liberacion/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='id_taller_subgrupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talleres.talleressubgrupos'),
            preserve_default=False,
        ),
    ]
