# Generated by Django 5.1.1 on 2024-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='requisito_asistencia',
        ),
        migrations.AddField(
            model_name='taller',
            name='dias_taller',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
