# Generated by Django 5.1.1 on 2024-11-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_rename_id_alumno_alumno_id_alum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='id_alum',
            new_name='id_alumno',
        ),
    ]
