# Generated by Django 5.1.1 on 2024-09-27 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_remove_taller_descripcion_remove_taller_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula_alumno',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'La matrícula debe tener exactamente 8 dígitos.')]),
        ),
    ]
