# Generated by Django 5.1.1 on 2024-11-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_remove_constancialiberacion_id_alumno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constancialiberacion',
            name='id_alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talleres.alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talleres.alumno'),
            preserve_default=False,
        ),
    ]
