# Generated by Django 5.1.1 on 2024-09-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_alter_alumno_matricula_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_paterno',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
    ]
