# Generated by Django 5.1.1 on 2024-11-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_rename_id_alum_alumno_id_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='matricula_alumno',
            new_name='matricula',
        ),
    ]
