# Generated by Django 5.1.1 on 2024-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_remove_alumno_apellidos_alumno_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='instructor',
            name='apellido_materno',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='apellido_paterno',
            field=models.CharField(default='No especificado', max_length=100),
            preserve_default=False,
        ),
    ]
