# Generated by Django 5.1.1 on 2024-11-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_rename_matricula_alumno_alumno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constancialiberacion',
            name='id_alumno',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_alumno',
        ),
    ]
