# Generated by Django 5.1.1 on 2024-10-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_remove_instructor_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.alumno')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.taller')),
            ],
        ),
    ]
