# Generated by Django 5.1.1 on 2024-11-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_remove_constancialiberacion_id_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id_alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
