# Generated by Django 5.1.1 on 2024-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0006_remove_alumno_id_alumno_alumno_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
