# Generated by Django 5.1.1 on 2024-10-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0007_nivelacceso_alumno_nivel_acceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nivel_acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.nivelacceso'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='nivel_acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.nivelacceso'),
        ),
    ]
