# Generated by Django 5.1.1 on 2024-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0008_alter_alumno_nivel_acceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
