# Generated by Django 5.1.1 on 2024-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0009_alter_instructor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contraseña',
            field=models.CharField(default='temp_password123', editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.EmailField(default='temp_password123', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='contraseña',
            field=models.CharField(default=2, editable=False, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioadmin',
            name='contraseña',
            field=models.CharField(default='temp_password123', editable=False, max_length=128),
            preserve_default=False,
        ),
    ]
