# Generated by Django 5.1.1 on 2024-10-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0010_alumno_contraseña_alumno_email_instructor_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalleresSupergrupo',
            fields=[
                ('id_taller_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=100)),
                ('estatus_taller', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='taller',
        ),
        migrations.CreateModel(
            name='TalleresSubgrupos',
            fields=[
                ('id_taller_registro', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_escolar', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('turno_taller', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('estatus_card', models.BooleanField(default=True)),
                ('dias_taller', models.CharField(max_length=200)),
                ('puntos_taller', models.IntegerField()),
                ('cupo_taller', models.IntegerField()),
                ('tipo_taller', models.CharField(max_length=100)),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.instructor')),
                ('id_taller_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.talleressupergrupo')),
            ],
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
