# Generated by Django 5.1.1 on 2024-10-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0011_talleressupergrupo_remove_inscripcion_taller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='alumno',
            new_name='matricula_alumno',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_taller_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='talleres.talleressubgrupos'),
            preserve_default=False,
        ),
    ]
