# Generated by Django 5.1.1 on 2024-10-22 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0012_rename_alumno_inscripcion_matricula_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaLiberacion',
            fields=[
                ('id_constancia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estatus_constancia', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Emitida', 'Emitida')], default='Pendiente', max_length=20)),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.inscripcion')),
                ('matricula_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.alumno')),
            ],
        ),
    ]
