# Generated by Django 5.1.1 on 2024-10-23 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0013_constancialiberacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('registro_participantes', models.FileField(blank=True, null=True, upload_to='reportes/participantes/')),
                ('evaluacion_desempeno', models.FileField(blank=True, null=True, upload_to='reportes/evaluacion/')),
                ('id_inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.inscripcion')),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.instructor')),
            ],
        ),
    ]
