# Generated by Django 5.1.1 on 2024-11-03 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0014_reporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constancialiberacion',
            old_name='matricula_alumno',
            new_name='id_alumno',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='matricula_alumno',
            new_name='id_alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula_alumno',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'La matrícula debe tener exactamente 8 dígitos.')]),
        ),
    ]
