# Generated by Django 5.1.1 on 2024-11-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0015_rename_matricula_alumno_constancialiberacion_id_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricaReportes',
            fields=[
                ('id_rubrica_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('registro_de_participantes', models.FileField(blank=True, null=True, upload_to='rubricas/participantes/')),
                ('evaluacion_desempeno', models.FileField(blank=True, null=True, upload_to='rubricas/evaluacion/')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='id_rubrica_reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talleres.rubricareportes'),
        ),
    ]
