# Generated by Django 5.1.1 on 2024-11-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0015_rubricareportes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
