# Generated by Django 5.1.1 on 2024-11-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0016_alter_alumno_id_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
