# Generated by Django 5.1.1 on 2024-11-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0016_rubricareportes_instructor_id_rubrica_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='id_rubrica_reporte',
        ),
    ]
